Finished rewrite, ci is now the main command

diff --git a/publisher b/publisher
--- a/publisher
+++ b/publisher
@@ -6,11 +6,21 @@ push_to_prod=${push_to_prod:- $3}
 # Read and parse configuration file
 # Prepare environment variables
 
-source env.sh
+if [ ! $ci_path ] || [ -z $ci_path ]; then
+    # Get the directory containing the script
+    ci_dir=$(dirname "$(readlink -f "$0")")
+
+    # Read and parse environment file
+    source $ci_dir/env.sh
+    path=$(getenv "CI_PATH")
+    ci_path="$path/projects"
+
+fi
+
 process_project_env "$ci_path/$project_alias/.env"
 config_file="$ci_path/$project_alias/deploy.json"
-if ! [ -f $config_file]; then
-    cat > "$config_file" <<EOF
+if [ ! -f $config_file ]; then
+    cat >"$config_file" <<EOF
 {
   "name": "App Name",
   "version": "0.0.0",
@@ -25,52 +35,46 @@ project_path=$(jq -r '.path' "$config_file")
 changelog=$(jq -r '.changelog' "$config_file")
 
 
-
-ci_path=$(getenv "CI_PATH")
-
 cd $project_path
 
-
-# Check if first argument is a command to check for the SemVer code 
+# Check if first argument is a command to check for the SemVer code
 # of the current version
 if [ "$deploy_type" = "current" ]; then
     echo "Current version is $project_version"
     exit 0
 fi
-# Check if first argument is a command to check for the SemVer code 
+# Check if first argument is a command to check for the SemVer code
 # of the next version, then swap values if true
 if [ "$deploy_type" = "next" ]; then
     action=$deploy_type
     deploy_type=$push_to_prod
 fi
 
-
 # Increment project_version based on deploy_type
 case $deploy_type in
-    major)
-        semver=( ${project_version//./ } )
-        ((semver[0]++))
-        project_version="${semver[0]}.0.0"
-        ;;
-    minor)
-        semver=( ${project_version//./ } )
-        ((semver[1]++))
-        project_version="${semver[0]}.${semver[1]}.0"
-        ;;
-    patch)
-        semver=( ${project_version//./ } )
-        ((semver[2]++))
-        project_version="${semver[0]}.${semver[1]}.${semver[2]}"
-        ;;
-    *)
-        echo "Invalid deploy_type. Valid values are major, minor, or patch."
-        exit 1
-        ;;
+major)
+    semver=(${project_version//./ })
+    ((semver[0]++))
+    project_version="${semver[0]}.0.0"
+    ;;
+minor)
+    semver=(${project_version//./ })
+    ((semver[1]++))
+    project_version="${semver[0]}.${semver[1]}.0"
+    ;;
+patch)
+    semver=(${project_version//./ })
+    ((semver[2]++))
+    project_version="${semver[0]}.${semver[1]}.${semver[2]}"
+    ;;
+*)
+    echo "Invalid deploy_type. Valid values are major, minor, or patch."
+    exit 1
+    ;;
 esac
 
-
 # Define paths
-ci_logs_path="$ci_path/logs"
+ci_logs_path="$path/logs"
 ci_project_path="$ci_path/$project_alias"
 log_file="$ci_logs_path/$(date '+%Y-%m-%d').log"
 ci_project_logs_path="$ci_path/$project_alias/logs"
@@ -81,9 +85,9 @@ ci_project_version_logs_path="$ci_path/$project_alias/logs/$project_version"
 
 # Function to print and log echo statements
 log_echo() {
-  local message="$1"
-  echo "$message"
-  echo "$(date '+%Y-%m-%d %H:%M:%S') - $message" >> "$log_file"
+    local message="$1"
+    echo "$message"
+    echo "$(date '+%Y-%m-%d %H:%M:%S') - $message" >>"$log_file"
 }
 
 # Function to exit on error
@@ -103,6 +107,7 @@ mkdir -p $ci_project_logs_path
 mkdir -p $ci_project_releases_path
 mkdir -p $ci_project_changelogs_path
 mkdir -p $ci_project_installers_path
+mkdir -p $ci_project_version_logs_path
 
 # Send the value of the next version
 if [ "$action" = "next" ]; then
@@ -121,7 +126,6 @@ if [ "$push_to_prod" = "create-changelog" ]; then
     exit 0
 fi
 
-
 # Check if second argument is a command to create installer, rather than to publish the code.
 # This is useful to both check the next version, and also create the installer file programmatically.
 if [ "$push_to_prod" = "create-installer" ]; then
@@ -131,59 +135,56 @@ if [ "$push_to_prod" = "create-installer" ]; then
     exit 0
 fi
 
-
 # Update configuration file with new project_version
-jq --arg new_version "$project_version" '.version = $new_version' "$config_file" > temp.json && mv temp.json "$config_file"
-jq --arg new_changelog "$ci_project_changelogs_path/$project_version.md" '.changelog = $new_changelog' "$config_file" > temp.json && mv temp.json "$config_file"
+jq --arg new_version "$project_version" '.version = $new_version' "$config_file" >temp.json && mv temp.json "$config_file"
+jq --arg new_changelog "$ci_project_changelogs_path/$project_version.md" '.changelog = $new_changelog' "$config_file" >temp.json && mv temp.json "$config_file"
 
 # Remove new lines from the configuration file
-config_content=$(tr -d '\n' < "$config_file")
+config_content=$(tr -d '\n' <"$config_file")
 
 # Create deploy_log.json if it doesn't exist
-if ! [ -f "$ci_project_logs_path/deploy_log.json"]; then
-    cat > "$ci_project_logs_path/deploy_log.json" <<EOF
+if ! [ -f "$ci_project_logs_path/deploy_log.json" ]; then
+    cat >"$ci_project_logs_path/deploy_log.json" <<EOF
 [
 
 ]
 EOF
 fi
 
-# projectend content to the second line of deploy_log.json
+# append content to the second line of deploy_log.json
 log_file="$ci_project_logs_path/deploy_log.json"
 tmp_file="$ci_project_logs_path/deploy_log_tmp.json"
 
-# Create a temporary file and projectend the updated config_content to it
-echo "[" > "$tmp_file"
-echo "$config_content" >> "$tmp_file"
-echo "," >> "$tmp_file"
+# Create a temporary file and append the updated config_content to it
+echo "[" >"$tmp_file"
+echo "$config_content" >>"$tmp_file"
+echo "," >>"$tmp_file"
 
-# projectend the existing content of deploy_log.json to the temporary file
-tail -n +2 "$log_file" >> "$tmp_file"
+# append the existing content of deploy_log.json to the temporary file
+tail -n +2 "$log_file" >>"$tmp_file"
 
 # Replace deploy_log.json with the temporary file
 mv "$tmp_file" "$log_file"
 
-
 rollback() {
-  log_echo "An error occurred. Rolling back changes..."
-  git checkout "$main_branch"
-  git branch -D "$project_version"
-  log_echo "Rolled back to $main_branch branch."
-  exit 1
+    log_echo "An error occurred. Rolling back changes..."
+    git checkout "$git_main_branch"
+    git branch -D "$project_version"
+    log_echo "Rolled back to $git_main_branch branch."
+    exit 1
 }
-
 
 # Make sure to be in the right folder
 cd $project_path
 
-# Archive the folder content, minding the instructions in .deployignore
+# Store the version codebase in a tarball, minding the instructions in .deployignore
 touch $ci_project_version_logs_path/tar_generate_error.log
-tar --exclude-ignore="$ci_project_path/.deployignore" v$project_version.tar.gz . > $ci_project_version_logs_path/tar_generate.log 2> $ci_project_version_logs_path/tar_generate_error.log
+
+tar --exclude-ignore="$ci_project_path/.deployignore" -cf "$ci_project_releases_path/v$project_version.tar.gz" . >$ci_project_version_logs_path/tar_generate.log 2>$ci_project_version_logs_path/tar_generate_error.log
 rc=$?
 check_error "Creating release tarball" $(cat $ci_project_version_logs_path/tar_generate_error.log)
 
-
-# Push to production if push_to_prod is 1
+# Push to production if push_to_prod is "push"
 if [ "$push_to_prod" = "push" ]; then
     #Move previous versions' installer script to the ci directory
     log_echo "Moving former versions' install scripts into .ci directory"
@@ -192,25 +193,60 @@ if [ "$push_to_prod" = "push" ]; then
         if [[ $file =~ ^[0-9]+\.[0-9]+\.[0-9]+\.sh$ ]] && [ "$file" != "$project_version.sh" ]; then
             # Move the file to the .ci directory
             mv "$file" "$ci_project_installers_path/"
-            log_echo "Moved $file to .ci directory."
+            log_echo "Moved $file to $project_alias's installers directory."
+        fi
+        if [ "$file" = "$project_version.sh" ]; then
+            # Copy the file to the .ci directory
+            cp "$file" "$ci_project_installers_path/"
+            log_echo "Copied $file to $project_alias's installers directory."
         fi
     done
+
     #Copy current version's installer to the ci directory
     log_echo "All previous installers moved, current version's installer has been copied.."
     log_echo "Creating release branch in current repo"
-    # Create and switch to the new branch
-    git checkout -b "$project_version" || rollback
+    push_to_git=$(getenv "GIT_PUSH")
+    git_remote_url=$(getenv "GIT_REMOTE_URL")
+    git_main_branch=$(getenv "GIT_MAIN_BRANCH")
 
-    # Push the codebase to the new branch
-    git push -u origin "$project_version" || rollback
+    # Check if $git_push is true
+    if [ $push_to_git = true ]; then
+    echo "Branching.."
+        # Check if git is already initialized
+        if ! [ -d .git ]; then
+            git init
+        fi
 
-    # Switch back to the main branch
-    git checkout "$main_branch"
+        # Check if $git_remote_url is already added as a remote URL
+        if ! git remote get-url "$project_alias" &>/dev/null; then
+            git remote add "$project_alias" "$git_remote_url"
+        fi
 
-    log_echo "Successfully created and pushed codebase to $project_version branch."
+        # Check if git user and email are set
+        if ! git config --get user.name &>/dev/null || ! git config --get user.email &>/dev/null; then
+            echo "Git user or email is not set. Please configure them using 'git config --global user.name' and 'git config --global user.email'."
+            exit 1
+        else
+            # Perform the git push
+            # git push "$project_alias"
+            # Create and switch to the new branch
+            echo "Creating new release branch: $project_version"
+            git checkout -b "$project_version" || rollback
+
+            echo "Pushing release code to branch $project_version"
+            # Push the codebase to the new branch
+            git push "$project_alias" -u "$project_version" || rollback
+
+            # Switch back to the main branch
+            git checkout "$git_main_branch"
+
+            log_echo "Successfully created and pushed codebase to $project_version branch."
+        fi
+    fi
+
     log_echo "Pushing to production..."
     VERSION=$project_version
-    source publish.sh
+    source "$path/publish.sh"
     # Add your deployment commands here
 else
     echo "Skipping production push."
